sudo: required
services:
  - docker

before_install:
  - docker build -t geonuta/docker_react_tutorial -f Dockerfile.dev . 
script:
  - docker run -e CI=true geonuta/docker_react_tutorial npm run test
deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "docker_react_tutorial"
  env: "Dockerreacttutorial-env"
  bucket_name: "elasticbeanstalk-eu-central-1-853376040332"
  bucket_path: "docker_react_tutorial"
  on:
    branch: master
  access_key_id: $ASW_ACCESS_KEY
  secret_access_key:
    secure: "$ASW_SECRET_KEY"