sudo: required
services:
  - docker

before_install:
  - docker build -t geonuta/docker_react_tutorial -f Dockerfile.dev . 
script:
  - docker run geonuta/docker_react_tutorial npm run test -- --coverage